name: "Close stale issues"
on:
  schedule:
    # hourly
    - cron: "0 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          only-labels: "Response Requested"
          stale-issue-message: "Greetings! It looks like this issue hasn't been active in longer than a week. Because it has been a while since the last update on this, and in the absence of more information, we will be closing this issue soon. Please feel free to provide a comment or add an upvote to prevent automatic closure, or if the issue is already closed, please feel free to open a new one."
          stale-issue-label: "Closing Soon"

          # Issue timing
          days-before-stale: 7
          days-before-close: 4

          # Temporarily run in debug mode
          # TODO: remove after verifying
          debug-only: true
